name: Atualizar Notícias

on:
  schedule:
    - cron: "0 */4 * * *"  # a cada 4 horas
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: pip install requests

      - name: Executar script
        env:
          NEWSDATA_API_KEY: ${{ secrets.NEWSDATA_API_KEY }}
        run: python .github/scripts/gerar_noticias.py

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add noticias.json
          git commit -m "Atualizando notícias via Newsdata.io" || echo "Nada novo para commitar"
          git push
