name: Atualizar Notícias

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests

      - name: Rodar gerador de notícias
        env:
          NEWSDATA_API_KEY: ${{ secrets.NEWSDATA_API_KEY }}
        run: python gerar_noticias.py

      - name: Commit e push das notícias
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add noticias.json

          if git diff --cached --quiet; then
            echo "Nenhuma atualização encontrada."
            exit 0
          fi

          git commit -m "Atualização automática de notícias"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
